// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW3Z0wTRdYOMmVTQ51l9EoxrKd0E7pBhY',
    appId: '1:468834203546:web:f069e6e902fc38578cac23',
    messagingSenderId: '468834203546',
    projectId: 'zkcnt-kanoon-pos',
    authDomain: 'zkcnt-kanoon-pos.firebaseapp.com',
    storageBucket: 'zkcnt-kanoon-pos.firebasestorage.app',
    measurementId: 'G-1EDB1TEM43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQMcyIduc1_l7YutYyS_7TxEbm1C7DgA',
    appId: '1:468834203546:android:2943141b31cac44a8cac23',
    messagingSenderId: '468834203546',
    projectId: 'zkcnt-kanoon-pos',
    storageBucket: 'zkcnt-kanoon-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZ3VujQMx8Z5zAIsOFfOFm6dociVhk-A',
    appId: '1:468834203546:ios:426a35575db36bd98cac23',
    messagingSenderId: '468834203546',
    projectId: 'zkcnt-kanoon-pos',
    storageBucket: 'zkcnt-kanoon-pos.firebasestorage.app',
    iosBundleId: 'com.example.flutterKanoonPos',
  );
}
